In [ ]:
import pandas as pd
import scanpy as sc

In [25]:
path = "C:/Users/vvval/Documents/EPFL/master/single_cell/"

In [26]:
df = pd.read_csv(path + "8_antenna.tsv.gz", compression='gzip', sep='\t')
df.head()

,128up,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.5542,0.5543,0.5544,0.5545,0.5546,0.5547,0.5548,0.5549,0.5550,0.5551
0,14-3-3epsilon,2,1,2,1,0,3,0,0,2,...,1,2,2,1,1,0,0,1,4,0
1,14-3-3zeta,3,0,3,0,4,2,2,3,6,...,0,3,3,4,0,1,0,0,7,0
2,140up,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,18SrRNA-Psi:CR41602,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,18w,0,0,0,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,0